// Generated by CoffeeScript 1.7.1
module.exports = {
  args: function(args, properties) {
    var argument, callback, i, options, _i, _len, _ref;
    if (args.length === 2 && typeof args[0] === 'object' && !Array.isArray(args[0])) {
      options = args[0];
      callback = args[1];
    } else {
      options = {};
      callback = args[args.length - 1];
      _ref = Array.prototype.slice.call(args).slice(0, args.length - 1);
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        argument = _ref[i];
        options[properties[i]] = argument;
      }
    }
    return [options, callback];
  }
};
